---
title: "Test import.R function
"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Cineqmembers<-function(mate)

```{r,echo=FALSE,warning=FALSE,message=FALSE }

library(stargazer)
#Load Libraries and functions
setwd("C:/Users/Christina/Desktop/mse-r/MSE-R")
source("mse.R")


```

## Example 1
```{r}
matchMatrix<- list(list(c(1,1),c(0,0),c(0,0)))
mate<-Cmate(matchMatrix)
print(mate)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(mate,list(list(list(c(1,2,3)),list(c(1,2),integer(0),integer(0)))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

```{r}
ineqmembers <- Cineqmembers(mate)
print(ineqmembers)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(ineqmembers,list(list(list(list(c(1,1,1),c(1,1,2)),list(c(1,1,1),c(1,1,2)),list()),list(list(c(1,2,1),c(1,2,2)),list(c(1,3,1),c(1,3,2)),list()))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

## Example 2
```{r}
matchMatrix<- list(list(c(1,1),c(1,0)))
mate<-Cmate(matchMatrix)
print(mate)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(mate,list(list(list(c(1,2)),list(c(1,2),c(1)))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

```{r}
ineqmembers <- Cineqmembers(mate)
print(ineqmembers)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(ineqmembers,list(list(list(list(c(1,1,1),c(1,1,2),c(1,2,1))),list(list(c(1,1,1),c(1,2,1),c(1,2,2))))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

## Example 3
```{r}
matchMatrix<- list(list(c(1,0),c(0,1)))
mate<-Cmate(matchMatrix)
print(mate)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(mate,list(list(list(c(1,2)),list(c(1),c(2)))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

```{r}
ineqmembers <- Cineqmembers(mate)
print(ineqmembers)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(ineqmembers,list(list(list(list(c(1,1,1),c(1,2,2))),list(list(c(1,1,2),c(1,2,1))))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

## Example 4
```{r}
matchMatrix<- list(list(c(0,1),c(1,0)))
mate<-Cmate(matchMatrix)
print(mate)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(mate,list(list(list(c(1,2)),list(c(2),c(1)))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

```{r}
ineqmembers <- Cineqmembers(mate)
print(ineqmembers)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(ineqmembers,list(list(list(list(c(1,1,2),c(1,2,1))),list(list(c(1,1,1),c(1,2,2))))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

## Example 5
```{r}
matchMatrix<- list(list(c(1,1),c(1,1)))
mate<-Cmate(matchMatrix)
print(mate)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(mate,list(list(list(c(1,2)),list(c(1,2),c(1,2)))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

```{r}
ineqmembers <- Cineqmembers(mate)
print(ineqmembers)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(ineqmembers,list(list(list(list(c(1,1,1),c(1,1,2),c(1,2,1),c(1,2,2))),list(list(c(1,1,1),c(1,2,1),c(1,2,2),c(1,1,2))))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

## Example 6
```{r}
matchMatrix<- list(list(c(1,1),c(0,1)),list(c(1,1,0),c(0,1,1),c(0,0,1)))
mate<-Cmate(matchMatrix)
print(mate)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(mate,list(list(list(c(1,2)),list(c(1,2),c(2))),list(list(c(1,2,3)),list(c(1,2),c(2,3),c(3)))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

```{r}
ineqmembers <- Cineqmembers(mate)
print(ineqmembers)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(ineqmembers,list(list(list(list(c(1,1,1),c(1,1,2),c(1,2,2))),list(list(c(1,1,2),c(1,2,1),c(1,2,2)))),list(list(list(c(2,1,1),c(2,1,2),c(2,2,2),c(2,2,3)),list(c(2,1,1),c(2,1,2),c(2,3,3)),list(c(2,2,2),c(2,2,3),c(2,3,3))),list(list(c(2,1,2),c(2,2,1),c(2,2,2),c(2,1,3)),list(c(2,1,3),c(2,3,1),c(2,3,2)),list(c(2,2,3),c(2,3,2),c(2,3,3))))),check.names=FALSE)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```