---
title: "Test maximize.R function"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

### Test functions in maximize.R file

```{r,warning=FALSE,message=FALSE }
#Load Libraries and functions
setwd("C:/Users/Christina/Desktop/mse-r/MSE-R")
source("mse.R")

#Import file
filename<-"import/round1m1-1.xls.pre.dat"
x<-import(filename)
g(header,noM,noU,noD,noAttr,distanceMatrices,matchMatrix,mate)%=%x


#Create inequality members
ineqmembers<-Cineqmembers(mate)

#Create Data Array
dataArray<-CdataArray(distanceMatrices,ineqmembers)

#Objective function
coefficient1<-1
b<-c(5,3) #Define x1,x2,... values
obj<-objective(b)

#maximize function
lower <- c(-10, -10)
upper <- -lower
par<-list(lower=lower,upper=upper,NP=50,itermax=100,trace=FALSE,reltol=0.001,CR=0.5,F=0.6,RandomSeed=0)
x<-maximize(par)
g(bestmem,bestval)%=%x
print(bestmem)

```

```{r,echo=FALSE}
temp<-ifelse(all.equal(as.character(bestmem),c("3.83352591911192","2.92996192006047"))==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```

```{r}
print(bestval)
```

```{r,echo=FALSE}
temp<-ifelse(all.equal(bestval,29966)==TRUE,print("Test Result: SUCCESS"),print("Test Result: TEST FAILED"))
```